<?php

declare(strict_types=1);

namespace Naf\CLI\Support;

use RuntimeException;
use stdClass;

/** Installs the host shortcut without booting the application or its services. */
final class LauncherInstaller
{
    public static function install(string $root, bool $addHook = true): void
    {
        $manifestPath = $root . '/composer.json';
        if (!is_file($manifestPath)) {
            throw new RuntimeException('Run naf-install from the application directory containing composer.json.');
        }
        $manifest = json_decode(file_get_contents($manifestPath), flags: JSON_THROW_ON_ERROR);
        if (!$manifest instanceof stdClass) {
            throw new RuntimeException('composer.json must contain an object.');
        }
        $vendor = $manifest->config->{'vendor-dir'} ?? 'vendor';
        $bin    = $manifest->config->{'bin-dir'} ?? $vendor . '/bin';
        foreach ([$vendor, $bin] as $path) {
            if (!is_string($path) || $path === '' || str_starts_with($path, '/') || str_contains($path, "\n") || str_contains($path, "\r")) {
                throw new RuntimeException('The launcher requires project-relative Composer vendor-dir and bin-dir paths.');
            }
        }
        if (rtrim($bin, '/') === 'bin') {
            throw new RuntimeException('Composer already manages bin/naf through config.bin-dir; no shortcut is needed.');
        }
        $binary  = self::quote(rtrim($bin, '/') . '/naf');
        $content = <<<'SH'
        #!/bin/sh
        # Generated by naf/cli. Runtime customizations belong in bin/naf-runtime.
        set -eu
        root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
        if [ -e "$root/bin/naf-runtime" ] || [ -L "$root/bin/naf-runtime" ]; then
            if [ ! -f "$root/bin/naf-runtime" ] || [ ! -x "$root/bin/naf-runtime" ]; then
                echo 'bin/naf-runtime must be an executable file.' >&2
                exit 1
            fi
            exec "$root/bin/naf-runtime" "$@"
        fi
        cd "$root"
        if [ ! -f __BINARY__ ]; then
            echo 'NAF console is not installed. Run composer install first.' >&2
            exit 1
        fi
        exec php __BINARY__ "$@"

        SH;
        $content = str_replace('__BINARY__', $binary, $content);
        $target  = $root . '/bin/naf';
        if (is_link($target) || (file_exists($target) && (!is_file($target) || file_get_contents($target) !== $content))) {
            throw new RuntimeException('bin/naf already exists and was left unchanged. Move it explicitly before installing the shortcut.');
        }
        // The hook tolerates removing naf/cli and never starts the application.
        $installer = var_export(rtrim($bin, '/') . '/naf-install', true);
        $hook      = '@php -r ' . self::quote('$GLOBALS["_naf_launcher_hook"] = true; if (is_file(' . $installer . ')) { require ' . $installer . '; }');
        $changed   = false;
        if ($addHook) {
            $hooks = $manifest->scripts->{'post-autoload-dump'} ?? [];
            $hooks = is_string($hooks) ? [$hooks] : $hooks;
            if (!is_array($hooks) || !array_is_list($hooks)) {
                throw new RuntimeException('scripts.post-autoload-dump must be a string or a list.');
            }
            if (!in_array($hook, $hooks, true)) {
                $manifest->scripts ??= new stdClass();
                $manifest->scripts->{'post-autoload-dump'} = [...$hooks, $hook];
                $changed                                   = true;
            }
        }
        if (!is_dir(dirname($target)) && !mkdir(dirname($target), 0775, true)) {
            throw new RuntimeException('Could not create the application bin directory.');
        }
        if (!file_exists($target)) {
            $file = fopen($target, 'x');
            if ($file === false) {
                throw new RuntimeException('Could not create bin/naf.');
            }

            try {
                if (fwrite($file, $content) !== strlen($content)) {
                    throw new RuntimeException('Could not write bin/naf.');
                }
            } finally {
                fclose($file);
            }
        }
        if (!is_executable($target) && !chmod($target, 0755)) {
            throw new RuntimeException('Could not make bin/naf executable.');
        }
        if ($changed) {
            $json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n";
            if (file_put_contents($manifestPath, $json) === false) {
                throw new RuntimeException('Could not register the launcher hook in composer.json.');
            }
        }
    }

    private static function quote(string $value): string
    {
        return "'" . str_replace("'", "'\\''", $value) . "'";
    }
}
